version: '3'
services:
  grocery-booking-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: "grocery"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"